const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const base = process.env.AMONG8_URL || 'http://127.0.0.1:8082';
const out = path.join(__dirname, 'artifacts'); fs.mkdirSync(out, { recursive: true });
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  try {
    const errors = [];
    const c1 = await browser.newContext({ viewport: { width: 390, height: 900 } });
    const c2 = await browser.newContext({ viewport: { width: 360, height: 900 } });
    const host = await c1.newPage(), guest = await c2.newPage();
    for (const p of [host, guest]) p.on('pageerror', e => errors.push(e.message));
    await host.goto(base); assert.equal(await host.locator('#player-name').count(), 0);
    await host.locator('[data-avatar="lime"]').click(); await host.locator('#create-button').click();
    await host.locator('.invite-code').waitFor(); const code = (await host.locator('.invite-code').innerText()).trim();
    assert.match(await host.locator('.lobby .player').first().innerText(), /Кваки/);
    await guest.goto(`${base.replace(/\/$/, '')}/?room=${code}`);
    await guest.waitForFunction(() => document.querySelector('[data-avatar="lime"]').classList.contains('occupied'));
    assert.equal(await guest.locator('[data-avatar="lime"]').isDisabled(), true);
    assert.match(await guest.locator('[data-avatar="lime"]').innerText(), /Занят/);
    await guest.screenshot({ path: path.join(out, 'character-occupied-mobile.png'), fullPage: true });
    assert.equal(await guest.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await guest.locator('[data-avatar="peach"]').click(); await guest.locator('#create-button').click();
    await host.getByRole('heading', { name: 'Оба здесь. Начинаем?' }).waitFor();
    assert.match(await host.locator('.lobby').innerText(), /Буба/);
    await host.locator('#start-match').click();
    for (const p of [host, guest]) await p.waitForFunction(() => document.querySelector('#squares')?.getAttribute('aria-disabled') === 'false');
    await host.locator('.square[data-value="37"]').click(); await guest.locator('.square[data-value="68"]').click();
    await host.locator('#main-action').click(); await guest.locator('#main-action').click();
    for (const p of [host, guest]) await p.locator('.result-box').waitFor();
    assert.deepEqual(await host.locator('.answers .answer-item p').allTextContents(), ['Кваки', 'Буба', 'Реальность']);
    assert.deepEqual(await guest.locator('.answers .answer-item p').allTextContents(), ['Кваки', 'Буба', 'Реальность']);
    await host.reload(); await host.locator('.result-box').waitFor(); assert.match(await host.locator('.mini-player').first().innerText(), /Кваки/);
    await host.locator('#leave-room').click(); await host.locator('[data-mode="solo"]').click();
    await host.locator('#create-button').click(); await host.locator('.board').waitFor();
    assert.match(await host.locator('.mini-player').innerText(), /Кваки/);
    await host.locator('#leave-room').click();
    // Changing a manually entered code must remove the old occupied state.
    await guest.locator('#return-home').waitFor(); await guest.locator('#return-home').click(); await guest.locator('#room-code').fill(code);
    await guest.waitForFunction(() => document.querySelector('[data-avatar="lime"]').classList.contains('occupied'));
    await guest.locator('#room-code').fill('');
    assert.equal(await guest.locator('[data-avatar="lime"]').isEnabled(), true);
    await host.locator('[data-mode="duel"]').click(); await host.locator('[data-avatar="plum"]').click(); await host.locator('#create-button').click();
    await host.locator('.invite-code').waitFor(); const secondCode = (await host.locator('.invite-code').innerText()).trim();
    await guest.goto(`${base.replace(/\/$/, '')}/?room=${secondCode}`);
    await guest.waitForFunction(() => document.querySelector('[data-avatar="plum"]').classList.contains('occupied'));
    assert.equal(await guest.locator('.avatar-option[aria-pressed="true"]').count(), 0, 'Do not silently assign a new character');
    assert.equal(await guest.locator('#create-button').isDisabled(), true);
    await guest.locator('[data-avatar="lime"]').click(); assert.equal(await guest.locator('#create-button').isEnabled(), true);
    await host.locator('#leave-room').click();
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({ passed: true, namesRemoved: true, occupiedCharacterDisabled: true, canonicalRevealNames: true, reconnect: true, solo: true, clearsOnCodeChange: true, errors }));
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
